### ISSUE TITLE
Double check config file and clean it up if needed

### ISSUE THREAD

**Issue by gutsy** [adobe/dynamic-workflow#30]
There's a number of items on the config that could be removed if they don't work. Review the config items and verify they are all a. being used b. actually work. 

```
# If hide_predefined is yes
  # HIDE ALL PREDEFINED RECIPIENTS ACROSS ALL WORKFLOWS:
  ## Comment out all the list items (-) by adding a # in front of it.
  # HIDE PREDEFINED RECIPIENTS WITH TARGET WORKFLOWS
  ## Add workflow names under hide_workflow_list such as " - Workflow name"
  hide_workflow_list:
    #- Notice how list items are comment out
    - "Workflow name here"
    - "Another workflow namer here"
  # This feature will hide predefined cc recipients within your workflow
  # yes to hide
  # no to show
  hide_cc: yes
  # If hide_cc is yes
  # HIDE ALL PREDEFINED CC RECIPIENTS ACROSS ALL WORKFLOWS:
  ## Comment out all the list items (-) by adding a # in front of it.
  # HIDE PREDEFINED CC RECIPIENTS WITH TARGET WORKFLOWS
  ## Add workflow names under hide_cc_workflow_list such as " - Workflow name"
  hide_cc_workflow_list:
    #- Notice how list items are comment out
    - "Workflow name here"
    - "Another workflow namer here"
```
